# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/806c05ab-d2e3-429c-a410-f70215c21524";
      fsType = "ext4";
    };

  # Enable swap on luks
  boot.initrd.luks.devices."luks-f53ea35c-04c8-4298-9ffb-3dfab4deb5c5".device = "/dev/disk/by-uuid/f53ea35c-04c8-4298-9ffb-3dfab4deb5c5";
  boot.initrd.luks.devices."luks-f53ea35c-04c8-4298-9ffb-3dfab4deb5c5".keyFile = "/crypto_keyfile.bin";
  boot.initrd.luks.devices."luks-0390cff2-76dd-46f2-a699-3023600f027b".device = "/dev/disk/by-uuid/0390cff2-76dd-46f2-a699-3023600f027b";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/CD29-FAE0";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6f2cbcfc-4cb9-4557-afc3-f77ea9b45b86"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
