k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 1000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: true
    showTime: true
  currentContext: ""
  currentCluster: ""
