theme = "plain"
icons = "awesome5"
scrolling = "reverse"

[[block]]
block = "net"
device = "wlp2s0"
#format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
format = "{signal_strength} {speed_down;K*b} {graph_down;K*b}"
interval = 5

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"
#on_click = "alacritty -t float_term -e bash -c 'watch docker ps'"
on_click = "dockeye"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
on_click = "alacritty -t float_term -e bash -c 'ncdu -x /'"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
on_click = "alacritty -t float_term -e 'htop'"

[[block]]
block = "load"
interval = 1
format = "{1m}"
on_click = "alacritty -t float_term -e 'glances'"

[[block]]
block = "backlight"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
