" colors
syntax enable
" tabs & spaces
set tabstop=4
set softtabstop=4
set expandtab
set smartindent
" UI Config
set number
set showcmd
set cursorline
set wildmenu
set lazyredraw
set showmatch
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey
" Searching
set incsearch
set hlsearch
" Movement
nnoremap j gj
nnoremap k gk
" pasting
set paste
" misc
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" actual plugins definitions
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

" Run PlugInstall if there are missing plugins
if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

