swipe:
  3:
    left:
      sendkey: 'LEFTALT+Left' # History back
      threshold: 1
      interval: 1
    right:
      sendkey: 'LEFTALT+Right' # History forward
      threshold: 1
      interval: 1
    up:
      sendkey: 'LEFTSHIFT+LEFTCTRL+Tab' # Previous Tab
      threshold: 1
      interval: 1
    down:
      sendkey: 'LEFTCTRL+Tab' # Next Tab
      threshold: 1
      interval: 1
  4:
    left:
      sendkey: 'BRIGHTNESSDOWN'
    right:
      sendkey: 'BRIGHTNESSUP'
    up:
      sendkey: 'VOLUMEUP'
    down:
      sendkey: 'VOLUMEDOWN'

      #pinch:
      #  2:
      #    in:
      #      sendkey: 'LEFTCTRL+EQUAL' # Zoom in
      #    out:
      #      sendkey: 'LEFTCTRL+MINUS' # Zoom out

threshold:
  pinch: 0.1
  swipe: 0.1

interval:
  swipe: 0.1
  pinch: 0.1

plugin: 
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
