# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# prompt
add_newline = false
right_format = """$time"""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold blue)"

# darkmode
#[username]
#show_always = true
#format = "[$user]($style)[@](fg:245)"
#style_user = "bold fg:250"
#
#[hostname]
#ssh_only = false
#style = "bold fg:250"
#format = "[$hostname]($style) [in](fg:245) "

[username]
show_always = true
format = "[$user]($style)[@](fg:240)"
style_user = "bold fg:235"

[hostname]
ssh_only = false
style = "bold fg:235"
format = "[$hostname]($style) [in](fg:240) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 5
truncation_symbol = '...'
truncate_to_repo = false

# darkmode
#[git_branch]
#format = "[on](fg:240) [$symbol$branch]($style) "

[git_branch]
format = "[on](fg:240) [$symbol$branch]($style) "

[git_metrics]
disabled = false

[kubernetes]
disabled = true

# darkmode
#[time]
#disabled = false
#style = "bold fg:235"
#format = "[at](fg:240) [$time]($style) "


[time]
disabled = false
style = "bold fg:235"
format = "[at](fg:240) [$time]($style) "


# disabled modules
[battery]
disabled = true
