# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# prompt
add_newline = false
right_format = """$time"""
command_timeout = 1000
format = "$all$kubernetes$shell$line_break$character"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold blue)"

[username]
show_always = true
format = "[$user]($style)[@](fg:245)"
style_user = "bold fg:250"

[hostname]
ssh_only = false
style = "bold fg:250"
format = "[$hostname]($style) "

[shell]
disabled = false
bash_indicator = '\(bash\) '
zsh_indicator = ''
format = '[$indicator](fg:245)'

[directory]
format = "[in](fg:245) [$path]($style)[$read_only]($read_only_style) "
truncation_length = 5
truncation_symbol = '...'
truncate_to_repo = false

[git_branch]
format = "[on](fg:245) [$symbol$branch]($style) "

[git_metrics]
disabled = false

[git_status]
disabled = false

[kubernetes]
disabled = false
detect_files = ['.k8s']
format = '[using](fg:245) [$symbol($cluster)\($namespace\)](blue) '


[time]
disabled = false
style = "bold fg:250"
format = "[at](fg:245) [$time]($style) "


# disabled modules
[battery]
disabled = true
